apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: app
          image: ghcr.io/blueswen/fastapi-observability/app:latest
          ports:
            - containerPort: 8000
          env:
            - name: OTLP_GRPC_ENDPOINT
              value: http://lgtm.observibility:4317

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - name: demo
      port: 8000
      targetPort: 8000
