apiVersion: v1
kind: Namespace
metadata:
  name: observibility
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lgtm-prometheus-config
  namespace: observibility
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
      scrape_native_histograms: true

    runtime:
      gogc: 75

    storage:
      tsdb:
        out_of_order_time_window: 10m
      exemplars:
        max_exemplars: 100000

    otlp:
      keep_identifying_resource_attributes: true
      promote_resource_attributes:
        - service.name
        - service.namespace
        - k8s.namespace.name
        - k8s.pod.name

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "demo-app"
        scrape_interval: 5s
        metrics_path: /metrics
        static_configs:
          - targets: ["demo-app.default:8000"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
  namespace: observibility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      containers:
        - name: lgtm
          image: grafana/otel-lgtm:latest
          ports:
            - containerPort: 3000   # Grafana UI
            - containerPort: 4317   # OTLP gRPC
            - containerPort: 4318   # OTLP HTTP
            - containerPort: 3100
          volumeMounts:
            - name: prometheus-config
              mountPath: /otel-lgtm/prometheus.yaml
              subPath: prometheus.yaml
      volumes:
        - name: prometheus-config
          configMap:
            name: lgtm-prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: lgtm
  namespace: observibility
spec:
  selector:
    app: lgtm
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: loki
      port: 3100
      targetPort: 3100