apiVersion: v1
kind: Namespace
metadata:
  name: observibility
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lgtm-prometheus-config
  namespace: observibility
data:
  prometheus.yaml: |

    global:
      scrape_native_histograms: true
    otlp:
      keep_identifying_resource_attributes: true
      # Recommended attributes to be promoted to labels.
      promote_resource_attributes:
        - service.instance.id
        - service.name
        - service.namespace
        - service.version
        - cloud.availability_zone
        - cloud.region
        - container.name
        - deployment.environment # backward compatibility
        - deployment.environment.name
        - k8s.cluster.name
        - k8s.container.name
        - k8s.cronjob.name
        - k8s.daemonset.name
        - k8s.deployment.name
        - k8s.job.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.name
        - k8s.replicaset.name
        - k8s.statefulset.name
        - host.name
        - postgresql.database.name
        - postgresql.schema.name
        - postgresql.table.name
        - postgresql.index.name
        - database # used by otelcol/receiver/mongodb
        - kafka.cluster.alias
    storage:
      tsdb:
        # A 10min time window is enough because it can easily absorb retries and network delays.
        out_of_order_time_window: 10m

    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: "prometheus"

        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.
        labels:
          app: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: 'demo-app'
        scrape_interval: 5s
        labels:
          app: "demo-app"
        static_configs:
          - targets: ['demo-app.default:8000']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
  namespace: observibility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      containers:
        - name: lgtm
          image: grafana/otel-lgtm:latest
          ports:
            - containerPort: 3000   # Grafana UI
            - containerPort: 4317   # OTLP gRPC
            - containerPort: 4318   # OTLP HTTP
            - containerPort: 3100
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /otel-lgtm/prometheus.yaml
              subPath: prometheus.yaml
      volumes:
        - name: prometheus-config
          configMap:
            name: lgtm-prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: lgtm
  namespace: observibility
spec:
  selector:
    app: lgtm
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: loki
      port: 3100
      targetPort: 3100
    - name: prometheus
      port: 9090
      targetPort: 9090